trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'lucasalvesdevv/unyleya-projeto-cicd-lucasalves'

steps:
- task: Docker@2
  displayName: 'Login no Docker Hub'
  inputs:
    command: login
    containerRegistry: 'DockerHubConnection'

- task: Docker@2
  displayName: 'Build e Push da imagem Docker'
  inputs:
    command: buildAndPush
    repository: '$(imageName)'
    dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)